archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    
    files:
      - none*

builds:
  -
    goos:
      - linux
      - darwin
      - windows
  
    goarch:
      - "386"
      - "amd64" 
    
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: true

changelog:
  skip: true
