name: Tag and Release

on: push

jobs:
  job1:
    name: Tag new version
    runs-on: ubuntu-latest
    outputs:
      previous_version: ${{ steps.create_tag.outputs.previous-version }}
      current_version: ${{ steps.create_tag.outputs.current-version }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: create_tag
        with:
          version-command: |
            grep -Po '\bVersion: "v\K.*?(?=")' cmd/root.go

  job2:
    name: Goreleaser
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ needs.job1.outputs.previous_version }} != ${{ needs.job1.outputs.current_version }}
    steps:
      - name: Echo version
        run: |
          echo ${{ needs.job1.outputs.previous_version }}
          echo ${{ needs.job1.outputs.current_version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
           
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
